import type { Metadata } from "next";
import { GeistSans, GeistMono } from 'geist/font';
import { Pacifico } from "next/font/google";
import "./globals.css";

// Fonts
const geist = GeistSans();
const mono = GeistMono();

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
});

export const metadata: Metadata = {
  title: "Readdy Site",
  description: "Generated by Readdy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${geist.className} ${mono.className} ${pacifico.variable} text-white bg-black`}>
        {children}
      </body>
    </html>
  );
}
